import ProjectNav from "./components/ProjectNav"
import Project from "./components/Project"
import { Link } from 'react-router-dom'
import loading from './images/loading.svg'
import Billing from './images/billing.png'
import QuizWeb from './images/quizweb.png'
import Invetory from './images/inventory.png'
import Mir4 from './images/mir4.png'

const ProjectWebsites = () => {
  return (
    <div className='container p-10 mx-auto flex sm:flex-row flex-col text-white inter-ff'>
      <ProjectNav />

      <div className="flex flex-col sm:mt-0 mt-14 sm:px-5 w-full">
        <div className="py-4 w-full">
          <h1 className="font-bold daysone-ff text-3xl text-center mb-5">WEBSITES</h1>
        </div>

        <div className="flex flex-wrap sm:justify-start justify-center gap-5 overflow-auto grow">

          <Project imgUrl={Billing} title='Billing Management System'
          description="This Billing Management System allows admin to track customer's finances through invoices,
                       receipts that are automatically generated by the system. The system was built using PHP, MYSQL, BOOSTRAP etc." />

          <Project imgUrl={QuizWeb} title='QuizIt' 
          description='QuizIt is an online learning platform that allows teachers (only) to create classes and quizzes
                      for their students. This was integrated with mobile platform where students can take quizzes through their mobile.
                      Languages used: PHP, MYSQL, VANILA CSS etc' />

          <Project imgUrl={Invetory} title='Inventory Management System'
          description='An inventory management system is a software or tool used by businesses to track, manage, and control their inventory
                      or stock of products. This was built using C#, SQL. ' />

          <Project imgUrl={Mir4} title='Mir4 Combine System' 
          description='I took the concept from a game MIR4 where pets/items can be
                      combine to get a greater type of pet by chance. It took me 3 weeks to finish the whole project.
                      This was built using only pure Javascript/Vanila JS' />
        </div>
      </div>
    </div>
  )
}

export default ProjectWebsites